services:
  postgres:
    image: pgvector/pgvector:pg16
    comtainer_name: comply
    environment:
      POSTGRES_USER: comply
      POSTGRES_PASSWORD: comply
      POSTGRES_DB: comply
    ports:
      - "5432":"5432"

    volumes:
      - comply_pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U comply -d comply"]
      interval: 3s
      timeout: 3s
      retries: 10
    restart:unless-stopped

  redis:
    image: redis:7-alpine
    container_name: comply-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 10
    restart: unless-stopped

 
volumes:
  comply_pgdata: